# Generated by Django 4.1 on 2022-08-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogitt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
